### PR TITLE
don't include missing/deleted documents that don't have 'id' set

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?186312b

up for grabs / @calellowitz / @snopoke

### CODE REVIEW

**Comment by czue** [comment]
:blowfish:

**Comment by calellowitz** [comment]
test failure definitely related. it doesnt like your setUpClass function. it may need a @classmethod decorator

**Comment by czue** [comment]
heh, i wonder how much https://github.com/classmethod gets pinged...

**Comment by czue** [comment]
:white_check_mark:

**Pull request merged**
