### PR TITLE
default elastic pillows to using sql checkpoints

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by czue** [comment]
wait for tests here and https://github.com/dimagi/commcare-hq/pull/9362

@snopoke cc @benrudolph

**Comment by snopoke** [comment]
:+1: waiting for tests on dimagi/commcare-hq#9362

**Comment by czue** [comment]
added sofabed pillows to this too, so probably worth taking another quick look

**Comment by snopoke** [comment]
:+1:

**Pull request merged**
