### PR TITLE
Change feed override

### PR DESCRIPTION
**Pull request by czue**
Changes to facilitate regular pillows actually using a different `ChangeFeed`

:blowfish: @calellowitz @snopoke 

going to test this on staging for a bit so don't merge

### CODE REVIEW

**Comment by czue** [comment]
alright I think this is :white_check_mark: from a qa perspective

**Comment by czue** [comment]
er i take it back - looking at one more thing

**Comment by emord** [comment]
Ran into issue deploying and the error was in pillowtop listener: (occured during flip_es_alias)

```
[hqdb0.internal.commcarehq.org] out: Traceback (most recent call last):
[hqdb0.internal.commcarehq.org] out:   File "manage.py", line 69, in <module>
[hqdb0.internal.commcarehq.org] out:     execute_from_command_line(sys.argv)
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from
_command_line
[hqdb0.internal.commcarehq.org] out:     utility.execute()
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
[hqdb0.internal.commcarehq.org] out:     self.fetch_command(subcommand).run_from_argv(self.argv)
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
[hqdb0.internal.commcarehq.org] out:     self.execute(*args, **options.__dict__)
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
[hqdb0.internal.commcarehq.org] out:     output = self.handle(*args, **options)
[hqdb0.internal.commcarehq.org] out:   File "submodules/pillowtop-src/pillowtop/management/commands/ptop_es_manage.py", line 82, in handle
[hqdb0.internal.commcarehq.org] out:     pillow.assume_alias()
[hqdb0.internal.commcarehq.org] out:   File "submodules/pillowtop-src/pillowtop/listener.py", line 647, in assume_alias
[hqdb0.internal.commcarehq.org] out:     if es.head(self.es_alias):
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/rawes/elastic.py", line 108, in head
[hqdb0.internal.commcarehq.org] out:     return self.request('head', path, **kwargs)
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/rawes/elastic.py", line 126, in request
[hqdb0.internal.commcarehq.org] out:     method, new_path, **kwargs)
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/rawes/http_connection.py", line 50, in request
[hqdb0.internal.commcarehq.org] out:     return self._decode(response, json_decoder)
[hqdb0.internal.commcarehq.org] out:   File "/home/cchq/www/production/releases/2015-11-12_20.39/python_env/local/lib/python2.7/site-packages/rawes/http_connection.py", line 64, in _decode
[hqdb0.internal.commcarehq.org] out:     result=decoded, status_code=response.status_code)
[hqdb0.internal.commcarehq.org] out: rawes.elastic_exception.ElasticException: (ElasticException(...), 'ElasticSearch Error: ')
[hqdb0.internal.commcarehq.org] out: 
```

Rolling back these changes on hq, but don't immediately see the issue here

**Comment by emord** [comment]
ignore previous comment. It looks like our prod ES got into a bad state and didn't have an alias for a bit for the  users db

**Comment by czue** [comment]
:+1: will still look into related issues

**Pull request merged**
