### PR TITLE
process chunk after max wait time

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?185327
@czue what do you think of this approach?

### CODE REVIEW

**Comment by czue** [comment]
seems fine, though 1 minute seems like a lot (I think this means every checkpoint will save every minute, right? so we'll get `# of pillows * 60 * 24 doc saves/revisions` per day? do we know what our save frequency on prod is now for the main db?

**Comment by czue** [comment]
(or does process_chunk not necessarily imply a checkpoint update)

**Comment by snopoke** [comment]
This won't change the frequency of checkpoint updates. It will only ensure
that the docs don't stay unprocessed if the frequency of changes is low

On 28 October 2015 at 10:09, Cory Zue <notifications@github.com> wrote:

> (or does process_chunk not necessarily imply a checkpoint update)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/pillowtop/pull/164#issuecomment-151758741>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by snopoke** [comment]
Based on a small sample size it looks like prod would process a chunk every ~70 seconds (given current usage)

**Pull request merged**
