### PR TITLE
migrate errors from the statuc ucr pillow rename

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?183437

@nickpell @snopoke

### CODE REVIEW

**Comment by calellowitz** [comment]
During deploy today this migration caused the following error:
```django.db.utils.IntegrityError: duplicate key value violates unique constraint "pillow_retry_pillowerror_doc_id_2f095e269b63b309_uniq"
DETAIL:  Key (doc_id, pillow)=(d51f1c1a-0fb1-4298-abbb-140797a578e8, corehq.apps.userreports.pillow.StaticDataSourcePillow) already exists.```
We changed hq to point one commit behind this pr merge for the deploy but could you fix this for next deploy.
@nickpell

**Comment by nickpell** [comment]
@czue Deploying prod without this migration seemed like the best approach, since it doesn't seem like a big deal if somewhere an instance of HQ ran this migration successfully and the migration history now records a successful migration that's no longer on HQ master, since a successful run of the migration means that the data is in the state desired.  happy to discuss if you think another approach is preferable (or if my run-on sentences don't make sense)

**Comment by czue** [comment]
@nickpell not sure I followed that.

the issue here would be if the same document failed when this pillow had the old name and the new name. i would have thought the simplest thing to do would have been to just catch that case and delete the row (since the other one would be newer). let me know if i should follow up on that.

i do think this should be run on prod - wasn't clear whether it was skipped or is still pending.

**Comment by nickpell** [comment]
Deleting the case sounds good to me - Just wanted to check with you since I
don't know this part of the code well

**Comment by czue** [comment]
https://github.com/dimagi/pillowtop/pull/149 - just to confirm - this will still be run on prod?

**Comment by nickpell** [comment]
Yes

**Pull request merged**
