### PR TITLE
sleep forever when encountering any error

### PR DESCRIPTION
**Pull request by czue**
@benrudolph what are your thoughts on this as a short term (pretty terrible) answer to the couchdbkit bug we just found

### CODE REVIEW

**Comment by czue** [comment]
context:

whenever you're iterating through a changes feed this context manager is in place https://github.com/dimagi/couchdbkit/blob/jsonobject/couchdbkit/changes.py#L47
which is one of these guys https://github.com/benoitc/restkit/blob/master/restkit/wrappers.py#L153
which, in the __exit__ method, tries to read the ENTIRE changes feed https://github.com/benoitc/restkit/blob/master/restkit/wrappers.py#L174
so anytime a pillow throws an error in a loop like this https://github.com/dimagi/pillowtop/pull/134/files#diff-6dac4be25b780fb79c406285662331fcR126
we try to read through the entire rest of the changes feed before exiting

**Comment by benrudolph** [comment]
this works? sounds better than what we were doing before, but also seems like we're going to be introducing some weird never ending loop bugs. any chance we can just change our fork? or do you think that will have bigger effects on couchdbkit as a whole?

**Comment by czue** [comment]
this works but agree it's super sketchy and was looking for feedback as to whether the tradeoffs weren't worth it. 

changing our fork sounds good too, i haven't completely wrapped my head around what that would look like though.

**Comment by czue** [comment]
(the idea here is that this should never happen, but if it does it will email us and stop the pillow - which is functionally equivalent to what it would do now except that it removes the overhead on couchdb)

**Comment by benrudolph** [comment]
not opposed to doing this, but as is, i didn't think it was urgent to get a fix in

**Comment by benrudolph** [comment]
actually thinking about this more, i'm more ok with it since essentially body.read() is an infinite loop anyways

**Comment by czue** [comment]
@benrudolph @snopoke @dannyroberts I'm thinking we should just merge this for now on the off change it's a source of cloudant slowness.

**Comment by snopoke** [comment]
Note that we did try replace the couchdbkit changes feed with python
request stream but had some issues with it that made us roll back. It could
be worth trying that (or something like that) again.

On 14 September 2015 at 14:29, Ben <notifications@github.com> wrote:

> Merged #134 <https://github.com/dimagi/pillowtop/pull/134>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/pillowtop/pull/134#event-408596000>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Pull request merged**
