### PR TITLE
tests and fixes for assume_alias

### PR DESCRIPTION
**Pull request by czue**
@snopoke :blowfish: (though some commits didn't end up in the final product)

### CODE REVIEW

**Comment by snopoke** [comment]
looks good but not mergable

**Comment by czue** [comment]
:white_check_mark:

**Comment by esoergel** [comment]
Just double checking - @czue Did you try deleting and rebuilding an index with this change?

**Comment by czue** [comment]
i did, why?

**Comment by esoergel** [comment]
Just making sure that was part of your test plan - it executes some different code paths which wouldn't have been run otherwise.

**Comment by czue** [comment]
yeah i think the issue was related to the chunking thing I found in https://github.com/dimagi/commcare-hq/pull/9113

**Pull request merged**
