### PR TITLE
remove autoretry_connection

### PR DESCRIPTION
**Pull request by czue**
looking at logs it seems this thing only really fires when elastic is down. proposing that we get rid of it and see if there are any bad side effects.

### CODE REVIEW

**Comment by czue** [comment]
(I think pillow retry also helps here though not 100% sure about that)

**Comment by czue** [comment]
probably good to wait for @snopoke or @dannyroberts to review/merge

**Comment by dannyroberts** [comment]
The concept seems good to me. I'm guessing this was added when our only plan for eventual consistency of pillow data was "don't mess up the first time"—I agree pillow retry takes care of this problem now so we don't have to be so desperate in the case of a rare network blip or something.

**Comment by dannyroberts** [comment]
0 additions and 40 deletions. At this rate, we'll soon have commcare-hq down to the desired 0 lines! Slowly but surely...

**Comment by snopoke** [comment]
:+1:

**Pull request merged**
