### PR TITLE
Changes refactor

### PR DESCRIPTION
**Pull request by czue**
main thing is defining a clear interface for changes and trying to isolate dependencies on actual couch changes feed to a single place

### CODE REVIEW

**Comment by czue** [comment]
@dannyroberts

**Comment by snopoke** [comment]
Looks good

**Comment by benrudolph** [comment]
:+1: :+1: :+1:

**Comment by czue** [comment]
I think this is good to go. @dannyroberts 

i can monitor from IST tomorrow

**Comment by dannyroberts** [comment]
:+1:

**Pull request merged**
